// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxuhttoeksdghgkywlst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dWh0dG9la3NkZ2hna3l3bHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDU5MDQsImV4cCI6MjA3ODk4MTkwNH0.2nTNG51P8INFieC2ThwYwefzi7zwXTWdu9JhIaZQyno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});